### PR TITLE
Updates CSS details, esthetics and animation plus reduced motion

### PR DESCRIPTION
**Pull request by NeelliJ**
Separating css changes from visualization changes

### CODE REVIEW

**Comment by NeelliJ** [comment]
Not sure about the conflict in CotimeInfo. Seems to be various changes on both sides

**Comment by mipodi** [comment]
I'm trying to fix the merge conflicts, hold on tight :), there are two files I need to fix even if it passes the checks

**Comment by mipodi** [comment]
This has become too complex for me, I don't know how do resolve it without either losing what I want to keep and what @zamzterz has added and also add the things @NeelliJ has done. Also I don't know how this reduced-motion works with the new library we are adding. Maybe we can talk about it on todays meeting?

**Comment by zamzterz** [comment]
I tried resolving the remaining conflicts, but looks like some needed files went missing earlier in the merge process (for example `lib/components/cotime/Events.svelte`).
I also took a look at the changes, and now that the "reduced motion" library is in place, it might possibly be simpler starting this PR over. What do you think? 🙂

**Comment by mipodi** [comment]
All right, @NeelliJ also suggested a new branch, great minds think alike! Also, .help-text in FullPageModal _is_ weirdly placed, I think that's where I went wrong with the accidentally centering the all of the modal, you know the Notion issue you also have Nellie.

**Pull request closed without merging**
