### PR TITLE
Cover canvas cutout with timestamp in snapshot.

### PR DESCRIPTION
**Pull request by zamzterz**
Fill in the area cutout to show the `CotimeInfo` component and cover it with the timestamp in the generated snapshot image.

This is an alternative to #128: it looks slightly uglier in the snapshot, but can be used if the visualisation really should cover that component at the top.

### CODE REVIEW

**Review by NeelliJ — COMMENTED** [review]
Cool cool cool! 
I like this version better. I think the font size feels much better, and it makes the text fit on phone screens.
On smaller screens it can cover teapots and stuff though. But maybe that's ok? I don't think it covers up that much, and we would have this problem regardless of where the text is placed on top of the visualisation.

Only thing I'd like to try is to give that buffer rectangle (or what would you call it?) a different color. Since it's gonna cover some things anyway, and call a little more attention to the timestamp on a larger screen snapshot. I'm thinking that we already have that kind of visual setup from seeing the thing move, with the samtid menu there. I mean it might not work but maybe it does?

**Comment by zamzterz** [comment]
@NeelliJ Thanks for the input and great idea about making it stand out more (instead of trying to hide it seamlessly)! I've changed it to use the same color as the samtid menu has in the live visualisation. How do you think that looks? (I personally think it looks good.)

**Comment by NeelliJ** [comment]
Interesting! Now it feels a bit like a clock on the wall to me.. I think I like it too.

**Comment by zamzterz** [comment]
Let's go with this then for now; it can always be fine-tuned (or restyled) later 👍

**Pull request merged**
